version: '3.8'

services:
  backend:
    build: ./backend
    container_name: honeypot-backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python app.py

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: honeypot-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: honeypot-network-dev
