# Docker Compose pour Honeypot Attack Map
# Orchestre les services backend et frontend

version: '3.8'

services:
  # Service Backend - FastAPI + SQLite
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: honeypot-backend
    ports:
      - "8000:8000"
    volumes:
      # Monter le répertoire de données pour persister la base SQLite
      - backend_data:/app/data
      # Optionnel : monter le code source pour le développement
      # - ../backend:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./data/honeypot_attacks.db
      - HONEYPOT_PORT=2222
      - GEOIP_API_URL=http://ip-api.com/json
      - LOG_LEVEL=INFO
    networks:
      - honeypot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - init-db

  # Service Frontend - React + Vite
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: honeypot-frontend
    ports:
      - "3000:3000"
    volumes:
      # Optionnel : monter le code source pour le développement
      # - ../frontend:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000
      - VITE_WS_URL=ws://backend:8000
      - VITE_APP_TITLE=Honeypot Attack Map
      - VITE_APP_VERSION=1.0.0
    networks:
      - honeypot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - backend

  # Service d'initialisation de la base de données
  init-db:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: honeypot-init-db
    volumes:
      - backend_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/honeypot_attacks.db
    networks:
      - honeypot-network
    command: ["python", "init_db.py"]
    restart: "no"

  # Service de génération de données de test (optionnel)
  populate-data:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: honeypot-populate-data
    volumes:
      - backend_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/honeypot_attacks.db
    networks:
      - honeypot-network
    command: ["python", "populate_fake_attacks.py"]
    depends_on:
      - init-db
    restart: "no"
    profiles:
      - demo

# Volumes nommés pour persister les données
volumes:
  backend_data:
    driver: local
    name: honeypot_backend_data

# Réseau interne pour la communication entre services
networks:
  honeypot-network:
    driver: bridge
    name: honeypot-network
    ipam:
      config:
        - subnet: 172.20.0.0/16
